server:
  port: 8080 # Valor por defecto si PORT no está configurado
spring:
  datasource:
    url: jdbc:sqlserver://sqlserver-db:1433;databaseName=master;encrypt=false
    username: sa
    password: YourStrong@Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update  # Puede ser 'create', 'update', 'validate' o 'none'
    show-sql: false  # Puede true o false, para ver las consultas SQL en consola

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html # Ruta para acceder a Swagger UI: http://localhost:8085/swagger-ui.html
